name: Send Daily WhatsApp Prayer

on:
  schedule:
    - cron: '30 11 * * *'  # Runs at 7:30 AM EST daily
  workflow_dispatch:       # Optional: lets you trigger manually from GitHub UI

jobs:
  send-prayer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily prayer script
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TO_WHATSAPP_NUMBER: ${{ secrets.TO_WHATSAPP_NUMBER }}
        TEMPLATE_SID: ${{ secrets.TEMPLATE_SID }}
      run: |
        python daily_prayer_bot.py
